version: "3.9"
services:
  websocket-gateway:
    volumes:
      # VSCode
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server-insiders/extensions
      # k8s
      - ~/.kube/config:/root/.kube/config
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - websocket-gateway

volumes:
  vscode-exts:
  vscode-exts-insiders:

networks:
  websocket-gateway:
