version: "3.9"
services:
  websocket-gateway:
    volumes:
      # VSCode
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server-insiders/extensions
      # Github CLI
      - ~/.config/gh:/root/.config/gh
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - kafka
    networks:
      - websocket-gateway

volumes:
  vscode-exts:
  vscode-exts-insiders:

networks:
  websocket-gateway:
