version: "3.9"
services:
  websocket-gateway:
    volumes:
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server-insiders/extensions
      - ~/.config/gh:/root/.config/gh
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8080:8080
    depends_on:
      - kafka
    networks:
      - websocket-gateway

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: ethereum-block-content:1:1,ethereum-block-number:1:1
    depends_on:
      - zookeeper
    networks:
      - websocket-gateway

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - websocket-gateway

volumes:
  vscode-exts:
  vscode-exts-insiders:

networks:
  websocket-gateway:
